[versions]
botella="0.1-SNAPSHOT"
kotlinxCoroutines="1.6.4"

[libraries]
# Kotlin and data types/structures related dependencies
botellaCommon = { module = "com.ai4traders:Botella-Common", version.ref = "botella"}
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines"}
kotlinxCoroutinesJvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinxCoroutines"}
kotlinxCoroutinesJdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinxCoroutines"}
kotlinxCoroutinesSlf4j = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-slf4j", version.ref = "kotlinxCoroutines"}
